import{readFileSync,writeFileSync,unlinkSync}from'node:fs';import{pathToFileURL}from'node:url';
const source=readFileSync('public/scene.js','utf8').replace("import * as THREE from '/three.js';", "import * as Base from 'three';const THREE={...Base,WebGLRenderer:class{constructor(){this.shadowMap={};}render(){}setPixelRatio(){}setSize(){}}};");
const path='public/.inspect-scene.mjs';writeFileSync(path,source);
const canvas=()=>({width:512,height:128,getContext(){return new Proxy({createRadialGradient:()=>({addColorStop(){}})},{get:(t,k)=>k in t?t[k]:(()=>{})});}});globalThis.document={createElement:canvas};globalThis.matchMedia=()=>({matches:false});
const {buildBathroom}=await import(pathToFileURL(process.cwd()+'/'+path));const world=buildBathroom(canvas());world.scene.updateMatrixWorld(true);const rows=new Map();let triangles=0;
const cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);
function area(poly){let sum=0;for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length];sum+=a[0]*b[1]-a[1]*b[0];}return Math.abs(sum)/2;}
function overlap(a,b){let poly=a,sign=Math.sign(cross(...b));for(let i=0;i<3;i++){const start=b[i],end=b[(i+1)%3],next=[];for(let j=0;j<poly.length;j++){const p=poly[j],q=poly[(j+1)%poly.length],dp=cross(start,end,p)*sign,dq=cross(start,end,q)*sign;if(dp>=-1e-8)next.push(p);if((dp>0&&dq<0)||(dp<0&&dq>0)){const t=dp/(dp-dq);next.push([p[0]+(q[0]-p[0])*t,p[1]+(q[1]-p[1])*t]);}}poly=next;if(poly.length<3)return 0;}return area(poly);}
world.scene.traverse(object=>{if(!object.isMesh)return;const p=object.geometry.attributes.position,index=object.geometry.index,m=object.matrixWorld.clone(),count=object.isInstancedMesh?object.count:1;for(let instance=0;instance<count;instance++){if(object.isInstancedMesh){object.getMatrixAt(instance,m);m.premultiply(object.matrixWorld);}else m.copy(object.matrixWorld);for(let i=0;i<(index?.count||p.count);i+=3){const vertices=[0,1,2].map(j=>new world.camera.position.constructor().fromBufferAttribute(p,index?index.getX(i+j):i+j).applyMatrix4(m));triangles++;if(vertices.some(v=>v.y<2.8))continue;for(const axis of ['x','y','z']){const coordinate=vertices[0][axis];if(!vertices.every(v=>Math.abs(v[axis]-coordinate)<1e-6))continue;const other=['x','y','z'].filter(a=>a!==axis),poly=vertices.map(v=>other.map(a=>v[a]));if(area(poly)<1e-8)continue;const key=axis+':'+coordinate.toFixed(5),list=rows.get(key)||[];list.push({poly,sign:Math.sign(cross(...poly)),mesh:object.uuid,color:object.material?.color?.getHexString(),triangle:i/3});rows.set(key,list);}}}});
const conflicts=[];for(const[plane,list]of rows)for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++){const a=list[i],b=list[j];if(a.sign!==b.sign)continue;const size=overlap(a.poly,b.poly);if(size>1e-5)conflicts.push({plane,area:size,a,b});}
writeFileSync('data/upper-inspection.json',JSON.stringify({triangles,conflicts},null,2));unlinkSync(path);console.log(JSON.stringify({triangles,conflicts:conflicts.length,examples:conflicts.slice(0,6)}));
