import{test}from'node:test';import assert from'node:assert/strict';import{once}from'node:events';import{mkdtempSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import WebSocket from'ws';import{startServer}from'../server.js';
function client(port){return new Promise(resolve=>{const ws=new WebSocket('ws://127.0.0.1:'+port+'/socket',{origin:'http://127.0.0.1:'+port}),messages=[],waiters=[];ws.on('message',b=>{const m=JSON.parse(b.toString()),i=waiters.findIndex(w=>w.type===m.type&&w.test(m));if(i>=0){const w=waiters.splice(i,1)[0];clearTimeout(w.timer);w.resolve(m);}else messages.push(m);});ws.on('open',()=>resolve({ws,send:m=>ws.send(JSON.stringify(m)),next(type,test=()=>true){const i=messages.findIndex(m=>m.type===type&&test(m));if(i>=0)return Promise.resolve(messages.splice(i,1)[0]);return new Promise((resolve,reject)=>{const w={type,test,resolve,timer:setTimeout(()=>reject(Error('Missing '+type)),2500)};waiters.push(w);});}}));});}

import{labelCrop,validateCrop}from'../public/labels.js';
import{tapeGrain}from'../public/tape-grain.js';
import{canStand}from'../public/walk.js';
import{defaultFurnishings}from'../public/furnishings.js';
test('label crops retain the front-frame aspect ratio and reject invalid bounds',()=>{for(const[w,h]of [[512,640],[512,512],[384,128]])for(const zoom of [1,2,6]){const c=labelCrop(w,h,zoom,0,1);assert.deepEqual(validateCrop(c,w,h),c);assert.ok(c.x>=0&&c.y>=0&&c.x+c.w<=1.00001&&c.y+c.h<=1.00001);}for(const bad of [{x:NaN,y:0,w:1,h:1},{x:0,y:0,w:.5,h:1},{x:1,y:0,w:1,h:1}])assert.throws(()=>validateCrop(bad,512,640));});
test('advanced tape grain is deterministic, changes over time and never makes opaque bars',()=>{const a=new Uint8ClampedArray(320*180*4),b=new Uint8ClampedArray(a.length),c=new Uint8ClampedArray(a.length);tapeGrain(a,320,180,129,1.6);tapeGrain(b,320,180,129,1.6);tapeGrain(c,320,180,130,1.6);assert.deepEqual(a,b);assert.notDeepEqual(a,c);for(let i=3;i<a.length;i+=4)assert.ok(a[i]<=62);});
test('open furniture leaves all sampled standing space connected and closes the vanity corner pocket',()=>{for(const mode of ['normal','drawers','doors']){const f=defaultFurnishings();f.curtainOpen=true;f.drawers=[mode==='drawers',false,false];f.doors=[mode==='doors',mode==='doors'];const free=new Set();for(let x=0;x<=130;x++)for(let z=0;z<=140;z++)if(canStand(-5.5+x*.1,-3.5+z*.1,f))free.add(x+','+z);const total=free.size,queue=[free.values().next().value];free.delete(queue[0]);for(let i=0;i<queue.length;i++){const[x,z]=queue[i].split(',').map(Number);for(const[dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]]){const key=(x+dx)+','+(z+dz);if(free.delete(key))queue.push(key);}}assert.equal(queue.length,total,mode+' must leave no isolated floor pockets');}const f=defaultFurnishings();f.doors[0]=true;assert.equal(canStand(-5.5,-1.4,f),false);});
test('public directory is opt-in, reserves four live seats atomically and honors host controls',async t=>{
 const app=startServer({port:0,database:':memory:'});await once(app.server,'listening');const port=app.server.address().port;t.after(()=>app.close());const list=async()=>await(await fetch('http://127.0.0.1:'+port+'/rooms')).json();
 const a=await client(port);a.send({type:'join',create:true,name:'Host',token:'a'.repeat(64)});const owner=(await a.next('joined')).id,code=(await a.next('state')).room.code;assert.deepEqual((await list()).rooms,[]);
 a.send({type:'listing',public:true,painting:true,name:'Mint open studio'});await a.next('state',m=>m.room.public);assert.equal((await list()).rooms[0].name,'Mint open studio');assert.ok(!JSON.stringify(await list()).includes('hash'));
 const guests=[];for(const key of ['b','c']){const b=await client(port);b.send({type:'join',publicJoin:true,code,name:'Guest',token:key.repeat(64)});await b.next('joined');await b.next('state');guests.push(b);}
 const rivals=await Promise.all(['d','e'].map(async key=>{const b=await client(port);b.send({type:'join',publicJoin:true,code,name:'Rival',token:key.repeat(64)});return b;}));
 const outcomes=await Promise.all(rivals.map(b=>Promise.race([b.next('joined').then(m=>({ok:true,b,id:m.id})),b.next('error').then(m=>({ok:false,b,error:m.message}))])));assert.equal(outcomes.filter(o=>o.ok).length,1);assert.match(outcomes.find(o=>!o.ok).error,/full/);assert.equal((await list()).rooms[0].online,4);
 const guest=guests[0];guest.send({type:'stroke',id:'public-paint',generation:0,tool:'squeeze',color:'#719b8c',size:.02,points:[[.3,.3]]});await guest.next('accepted');guest.send({type:'listing',public:false,painting:false,name:''});assert.match((await guest.next('error')).message,/host/);
 a.send({type:'listing',public:false,painting:false,name:'Mint private studio'});await a.next('state',m=>!m.room.public);assert.deepEqual((await list()).rooms,[]);const outsider=await client(port);outsider.send({type:'join',publicJoin:true,code,name:'Late guest',token:'f'.repeat(64)});assert.match((await outsider.next('error')).message,/no longer/);
 guest.send({type:'stroke',id:'private-denied',generation:0,tool:'squeeze',color:'#719b8c',size:.02,points:[[.3,.3]]});assert.match((await guest.next('error')).message,/owner/);
 const kicked=outcomes.find(o=>o.ok);a.send({type:'kick',player:kicked.id});await once(kicked.b.ws,'close');const returning=await client(port);returning.send({type:'join',code,name:'Removed guest',token:(kicked.b===rivals[0]?'d':'e').repeat(64)});assert.match((await returning.next('error')).message,/removed/);assert.notEqual(owner,kicked.id);
});
test('personal label snapshots preserve the chosen crop and artwork across washing and restart',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'bathroom-label-')),database=join(dir,'studio.sqlite');let now=100000,app=startServer({port:0,database,clock:()=>now});await once(app.server,'listening');let port=app.server.address().port;t.after(async()=>{await app.close();rmSync(dir,{recursive:true,force:true});});const a=await client(port),b=await client(port);
 a.send({type:'join',create:true,name:'Label artist',token:'1'.repeat(64)});const owner=(await a.next('joined')).id,code=(await a.next('state')).room.code;b.send({type:'join',code,name:'Viewer',token:'2'.repeat(64)});await b.next('joined');await b.next('state');const crop=labelCrop(512,640,2,.7,.3),request={type:'label',surface:'towel',generation:0,sequence:1,crop};a.send(request);assert.match((await a.next('error')).message,/closer/);
 a.send({type:'stroke',id:'label-study',generation:0,tool:'squeeze',color:'#ef7066',size:.02,points:[[.2,.2],[.8,.8]]});await a.next('accepted');const move=async(x,z)=>{now+=1000;a.send({type:'move',pose:{x,z,yaw:0}});await b.next('pose',m=>m.player===owner&&m.pose.x===x&&m.pose.z===z);};for(const[x,z]of [[.3,1.7],[.3,3.8],[.3,5.1],[.3,6.5],[2.5,6.5],[4.7,6.5]])await move(x,z);
 a.send({...request,crop:{x:1,y:0,w:1,h:1}});assert.match((await a.next('error')).message,/crop/);a.send(request);const label=(await b.next('label')).label;assert.equal(label.strokes[0].id,'label-study');assert.deepEqual(label.crop,crop);
 for(const[x,z]of [[2.3,6.5],[.3,6.5],[-1,7.7],[-2.2,7.7]])await move(x,z);a.send({type:'furnishing',fixture:'washer'});await a.next('state',m=>m.room.laundry.phase==='washing');now+=20000;a.send({type:'sync'});const washed=(await a.next('state',m=>m.room.laundry.phase==='wet')).room;assert.equal(washed.strokes.length,0);assert.equal(washed.labels[0].strokes[0].id,'label-study');
 await app.close();app=startServer({port:0,database,clock:()=>now});await once(app.server,'listening');port=app.server.address().port;const recovered=await client(port);recovered.send({type:'join',code,name:'Label artist',token:'1'.repeat(64)});await recovered.next('joined');const room=(await recovered.next('state')).room;assert.deepEqual(room.labels[0].crop,crop);assert.equal(room.labels[0].strokes[0].id,'label-study');assert.equal(room.strokes.length,0);recovered.send({type:'unstuck'});const pose=(await recovered.next('pose',m=>m.recovery)).pose;assert.ok(canStand(pose.x,pose.z,room.furnishings));assert.equal(pose.support,undefined);
});
